Models/Contacto.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace piraña.Models
{
    [Table("Contacto")]
    public class Contacto
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("ID")]
        public int ID { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese nombre")]
        [Display(Name = "Nombre")]
        [Column("Nombre")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese su apellido")]
        [Display(Name = "Apellido")]
        [Column("Apellido")]
        public string Apellido { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese un e-mail para contactarlo")]
        [RegularExpression(@"^[^@\s]+@[^@\s]+\.[^@\s]+$", ErrorMessage = "No es un e-mail válido")]
        [Display(Name = "Email")]
        [Column("Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Debe ingresar un número de teléfono")]
        [StringLength(9)]
        [RegularExpression(@"[0-9]{9}", ErrorMessage = "No es un número de teléfono válido")]
        // [DataType(DataType.PhoneNumber)]
        [Display(Name = "Teléfono")]
        [Column("Telefono")]
        public string Telefono { get; set; }

        [Display(Name = "Asunto")]
        [Column("Asunto")]
        public string Asunto { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese un mensaje")]
        [Display(Name = "Mensaje")]
        [Column("Mensaje")]
        public string Mensaje { get; set; }

        [NotMapped]
        public string Respuesta { get; set; }

    }
}

Models/ErrorViewModel.cs
using System;

namespace piraña.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ConocenosController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using piraña.Controllers;

namespace LibreriaProgra.Controllers
{
    public class ConocenosController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public ConocenosController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

Controllers/ContactenosController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using piraña.Controllers;

namespace LibreriaProgra.Controllers
{
    public class ContactenosController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public ContactenosController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using piraña.Models;

namespace piraña.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/Rest/ContactoController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using piraña.Data;
using piraña.Models;

namespace Vivero.Controllers
{
    public class ContactoController : Controller
    {
         private readonly ILogger<ContactoController> _logger;
         private readonly ApplicationDbContext _context;

        public ContactoController(ILogger<ContactoController> logger,
        ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            var listContactos=_context.Contacto.Where(x => x.Mensaje != null).ToList();
            return View(listContactos);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Contacto contacto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contacto);
                _context.SaveChanges();
                contacto.Respuesta="Gracias " + contacto.Nombre + ", lo contactaremos lo más pronto posible.";
                return RedirectToAction("ContactoConfirmacion", contacto);
            }

            return View(contacto);
        }

        //confirmacion
        public IActionResult ContactoConfirmacion(Contacto c)
        {
            return View("ContactoConfirmacion",c);
        }
        // ObtenerContacto
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contacto = await _context.Contacto.FindAsync(id);
            if (contacto == null)
            {
                return NotFound();
            }
            return View(contacto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nombre,Apellido,Email,Telefono")] Contacto contacto)
        {
            if (id != contacto.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contacto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                    
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contacto);
        }
        

   
        public IActionResult Delete(int? id)
        {
            var contacto = _context.Contacto.Find(id);
            _context.Contacto.Remove(contacto);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

Views/Contactenos/Index.cshtml
@{
    ViewData["Title"] = "Conocenos";
}

 <div class="section-title">
          <h2 data-aos="fade-in"> Conocenos </h2>

        </div>

     <section id="about" class="about section-bg">
      <div class="container">

        <div class="row">
          <div class="image col-xl-5 d-flex align-items-stretch justify-content-center justify-content-lg-start">

              <img src="~/img/biblioteca.jpg" style="height: 400px; width: 480px"  >
          </div>
          <div class="col-xl-7 pl-0 pl-lg-5 pr-lg-1 d-flex align-items-stretch">
            <div class="content d-flex flex-column justify-content-center">
              <h3 data-aos="fade-in" data-aos-delay="100"> La piraña </h3>
              <p data-aos="fade-in">
                La piraña es una una tienda infantil donde podras encontrar toda clase de cosas cumpleañeras
              </p>
              <div class="row">
                <div class="col-md-6 icon-box" data-aos="fade-up">
                  <i class="bx bx-receipt"></i>
                  <h4><a href="#">Globos de excelentes calidad </a></h4>
                  <p>piñatas importantes de diferentes empresass</p>
                </div>
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
                  <i class="bx bx-images"></i>
                  <h4><a href="#">Objetos cumpleañeras</a></h4>
                  <p>nuestros servicios son los mejores</p>
                </div>
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="200">
                  <i class="bx bx-pencil"></i>
                  <h4><a href="#">Las mejores piñatas</a></h4>
                  <p>Tenemos toda clase de piñatas para cada fiesta</p>
                </div>
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="300">
                  <i class="bx bx-shield"></i>
                  <h4><a href="#">Protección</a></h4>
                  <p>No esta hecho con productos toxicos para la salud</p>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </section>

  <footer id="footer">

    <div class="footer-top">

      <div class="container" data-aos="fade-up">

        <div class="row  justify-content-center">
          <div class="col-lg-6">
            <h3>La piraña</h3>
            <p>Dirección: Av La Molina, 305 Las gardenias </p>
            <p>Telefono: +51 996644587</p>
          </div>
        </div>

        

        <div class="social-links">
          <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
          <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
          <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
          <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
          <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
 
    </div>

    <div class="container footer-bottom clearfix">
      <div class="copyright">
        &copy; Copyright <strong><span> Copyright</span></strong>. Todos los derechos reservador
      </div>
      <div class="credits">
        Diseñado por <a href="#">La piraña</a>
      </div>
    </div>
  </footer>

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

Views/Contacto/ContactoConfirmacion.cshtml
@model piraña.Models.Contacto

@{
    ViewData["Title"] = "Contacto";
}
<h3>Formulario enviado</h3>
<td>@Html.DisplayTextFor(c => c.Respuesta)</td>

Views/Contacto/Create.cshtml
@model piraña.Models.Contacto

@{
    ViewData["Title"] = "Contacto";
}

<div class="row">
    <div class="col-md-4">  
        <h1 class="display-4">Contacto</h1>
        <form asp-controller="Contacto" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>    

            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>               
                   
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
            </div>               

            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
            </div>               

            <div class="form-group">
                <label asp-for="Asunto" class="control-label"></label>
                <input asp-for="Asunto" class="form-control" />
            </div>    

            <div class="form-group">
                <label asp-for="Mensaje" class="control-label"></label>
                <textarea asp-for="Mensaje" class="form-control">
                    <span asp-validation-for="Mensaje" class="text-danger"></span>
                </textarea>
            </div>                

            <div class="form-group">
                 <button type="submit" class="btn btn-primary">Enviar</button> 
            </div>                

        </form>
            
        <td>@Html.DisplayTextFor(model => model.Respuesta)</td>    
    
    </div>
</div>

Views/Contacto/Edit.cshtml
@model piraña.Models.Contacto

@{
    ViewData["Title"] = "Contacto";
}

<div class="row">
    <div class="col-md-4">  
        <h1 class="display-4">Editar Contacto</h1>
        <form asp-controller="Contacto" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>    

            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>               
                   
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
            </div>               

            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
            </div>               

            
            <div class="form-group">
                 <button type="submit" class="btn btn-primary">Actualizar</button> 
            </div>                

        </form>
            
        <td>@Html.DisplayTextFor(model => model.Respuesta)</td>    
    
    </div>
</div>

Views/Contacto/Index.cshtml
@model IEnumerable<Contacto>

<h2>Lista Contactos</h2>

<p>
    <a asp-action="Create">Crear contacto</a>
</p>
<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
                <th scope="col">
                    Acción
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Nombre)
                </th> 
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Apellido)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Mensaje)
                </th>
        </tr>
    </thead>

    <tbody>

    @if (Model.Count() == 0) {
            <tr>
                <td colspan="5" class="text-center">No se encontraron registros.</td>
            </tr>
    }

    @foreach (var item in Model)
    {
        <tr>
            <th scope="row">
                <a asp-action="Edit" asp-route-id="@item.ID">Editar</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Borrar</a>
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mensaje)
            </td>
        </tr>
    }        
    </tbody>    
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - piraña</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">piraña</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item center">
                            <a class="nav-link colorLetter" class="center" asp-controller="Contactenos" asp-action="Index">Conocenos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Create">Contacto</a>
                        </li> 
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - piraña - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>